version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: flexxus_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${DB_NAME}
      MYSQL_USER:          ${DB_USER}
      MYSQL_PASSWORD:      ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: flexxus_adminer
    restart: unless-stopped
    ports:
      - '8080:8080'

volumes:
  db_data:
